sudo: false

language: node_js

dist: bionic

node_js:
  - "10.15.3"
  - "stable"

cache:
  npm: true
  directories:
    - node_modules

before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

install:
  - npm install

script:
  - ./build.sh

matrix:
  allow_failures:
    - node_js: "stable"
