sudo: false

language: node_js

node_js:
  - "6.10.2"
  - "stable"

services:
  - docker

cache: yarn

script:
  - npm test
  
deploy:
  provider: npm
  email: "dev@diabeloop.fr"
  skip_cleanup: true
  on:
    tags: false
    all_branches: true

matrix:
  allow_failures:
    - node_js: "stable"
