language: node_js

os: linux
dist: bionic

env:
  global:
    - SECURITY_SCAN=false
    - NODE_OPTIONS='--max-old-space-size=4096'

jobs:
  include:
    - node_js: lts/*

cache: npm
services:
  - docker
addons:
  chrome: stable
  firefox: latest-esr

before_install:
  - npm install -g npm@latest
  - npm cache verify
  - rm -fv ~/.npm/_logs/*

install:
  - npm install

deploy:
  # Deploy SOUP list
  - provider: s3
    edge: true
    on:
      tags: true
      node_js: lts/*
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    region: $AWS_DEFAULT_REGION
    bucket: com.diabeloop.yourloops.doc
    cleanup: false
    local_dir: doc
    upload_dir: soup/blip
    cache_control: "max-age=21600"

script:
  - npm run info
  - npm run lint
  - npm run test
  - npm run security-checks
  - bash artifact.sh
  - bash show-npm-logs.sh
