language: node_js

os: linux
dist: bionic

env:
  global:
    - SECURITY_SCAN=false
    - nexus_token=$NEXUS_TOKEN

jobs:
  include:
    - node_js: 10.15.3
    - node_js: lts/*
  allow_failures:
    - node_js: lts/*

cache: npm
services:
  - docker
addons:
  chrome: stable
  firefox: latest-esr

before_install:
  - npm install -g npm@latest
  - npm cache verify
  - rm -fv ~/.npm/_logs/*

install:
  - npm install

deploy:
  # Control deployment by setting a value for `on`. Setting the `branch`
  # option to `master` means Travis will only attempt a deployment on
  # builds of your repo's master branch (e.g., after you merge a PR).
  # Deploy SOUP list
  - provider: s3
    edge: true
    on:
      tags: true
      node_js: 10.15.3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    region: $AWS_DEFAULT_REGION
    bucket: com.diabeloop.yourloops.doc
    cleanup: false
    local_dir: doc
    upload_dir: soup/blip
    cache_control: "max-age=21600"

script:
  - npm run info
  - npm run lint
  - npm run test
  - npm run security-checks
  - bash server/update-version.sh
  - npm run clean
  - bash build.sh
  - bash show-npm-logs.sh
