sudo: false

language: node_js

dist: trusty

node_js:
  - "10.14.2"
  - "stable"

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

install:
  - yarn install --frozen-lockfile
  - NODE_ENV=production npm run build

script:
  - "npm test"

matrix:
  allow_failures:
    - node_js: "stable"
