language: node_js

os: linux
dist: bionic

env:
  global:
    - SECURITY_SCAN=false
    - NODE_OPTIONS='--max-old-space-size=4096'

jobs:
  include:
    - node_js: lts/*

cache: npm
services:
  - docker
addons:
  chrome: stable
  firefox: latest-esr

before_install:
  - npm install -g npm@latest
  - npm cache verify
  - rm -fv ~/.npm/_logs/*

install:
  - npm install

script:
  - npm run lint
  - npm run test
  - npm run security-checks
  - bash build.sh
