sudo: false

language: node_js

node_js:
  - 6.10.2
  - node

cache: yarn

before_install:
  - if [[ `npm -v` != 4* ]]; then npm install -g npm@4; fi
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.27.5
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn install --frozen-lockfile

deploy:
  # Control deployment by setting a value for `on`. Setting the `branch`
  # option to `master` means Travis will only attempt a deployment on
  # builds of your repo's master branch (e.g., after you merge a PR).
  on:
    tags: true
    node_js: 6.10.2
#    branch: dbl
  provider: s3
  # You can refer to environment variables from Travis repo settings!
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: $AWS_DEFAULT_REGION
  # Name of the S3 bucket to which your site should be uploaded.
  bucket: $AWS_BUCKET
  # Prevent Travis from deleting your built site so it can be uploaded.
  skip_cleanup: true
  # Path of the source directory containing your built site.
  local_dir: deploy
  # Path to a directory containing your built site.
  upload-dir: deploy
  # Set the Cache-Control header.
  cache_control: "max-age=21600"

services:
  - docker

script:
  - npm run lint
  - npm test
  - ./artifact.sh

matrix:
  allow_failures:
    - node_js: node
