sudo: false

language: node_js

dist: trusty

node_js:
  - 10.15.3
  - node

cache: npm

env:
  jobs:
    - BUILD_SOUP=true

before_install:
  - if [[ `npm -v` != 6* ]]; then npm install -g npm@6; fi

install:
  - npm install
  - npm install --save-dev ci-toolbox@2.1.1

deploy:
  - provider: s3
    on:
      tags: true
      node_js: 10.15.3
    # You can refer to environment variables from Travis repo settings!
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    region: $AWS_DEFAULT_REGION
    # Name of the S3 bucket to which your site should be uploaded.
    bucket: $AWS_BUCKET
    # Prevent Travis from deleting your built site so it can be uploaded.
    skip_cleanup: true
    # Path of the source directory containing your built site.
    local_dir: deploy
    # Path to a directory containing your built site.
    upload-dir: deploy
    # Set the Cache-Control header.
    cache_control: "max-age=21600"
  # Deploy SOUP list
  - provider: s3
    on:
      tags: true
    # You can refer to environment variables from Travis repo settings!
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    region: $AWS_DEFAULT_REGION
    # Name of the S3 bucket to which your site should be uploaded.
    bucket: com.diabeloop.yourloops.doc
    # Prevent Travis from deleting your built site so it can be uploaded.
    skip_cleanup: true
    # Path of the source directory containing your built site.
    local_dir: doc
    # Path to a directory containing your built site.
    upload-dir: soup/blip
    # Set the Cache-Control header.
    cache_control: "max-age=21600"

services:
  - docker

addons:
  chrome: stable

script:
  - npm test
  - ./artifact.sh

matrix:
  allow_failures:
    - node_js: node
