sudo: false

language: node_js

node_js:
  - "6.10.2"
  - "stable"

services:
  - docker

script:
  - yarn 
  - npm test
  - ls -la
  - npm publish
  - ls -la
  
matrix:
  allow_failures:
    - node_js: "stable"
