files:
  - source: /locales/en/translation.json
    translation: /locales/%two_letters_code%/%original_file_name%
    update_option: update_as_unapproved
  - source: /locales/en/yourloops.json
    translation: /locales/%two_letters_code%/%original_file_name%
    update_option: update_as_unapproved
