#on:
#  workflow_call:
#    inputs:
#      head-ref:
#        required: true
#        type: string
#      image-tag:
#        required: true
#        type: string
#      commit-sha:
#        required: false
#        type: string

name: 'Publish action'

inputs:
  head-ref:
    required: true
    type: string
  image-tag:
    required: true
    type: string
  commit-sha:
    required: false
    type: string

outputs:
  version: ${{ steps.changelog-version.outputs.semver }}

runs:
  using: 'composite'
#    runs-on: ubuntu-latest

  steps:
    - name: Checkout files
      uses: actions/checkout@v3
      with:
        ref: ${{ inputs.head-ref }}

    - name: Download artifact
      uses: actions/download-artifact@v3

    #      - name: Get YourLoops version from changelog
    #        uses: addnab/docker-run-action@v3
    #        with:
    #          username: ${{ secrets.NEXUS_USERNAME }}
    #          password: ${{ secrets.NEXUS_PASSWORD }}
    #          registry: ${{ secrets.REGISTRY }}
    #          options: -v ${{ github.workspace }}:/dblprm/blip:rw --user 0:0
    #          image: docker.ci.diabeloop.eu/ci-toolbox:latest
    #          run: |
    #            cd blip
    #            echo "semver=$(release-helper get-version)" > version.env
    #
    #      - name: Read env file
    #        id: changelog-version
    #        uses: cardinalby/export-env-action@v1
    #        with:
    #          envFile: 'version.env'
    #          expand: 'false'
    #          export: 'false'

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        driver-opts: |
          image=moby/buildkit:v0.10.6

    - name: Log in to the Nexus registry
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.REGISTRY }}
        username: ${{ secrets.NEXUS_USERNAME }}
        password: ${{ secrets.NEXUS_PASSWORD }}

    - name: Build and push blip Docker image
      uses: docker/build-push-action@v3.2.0
      with:
        context: .
        push: true
        platforms: linux/arm64,linux/amd64
        tags: ${{ secrets.REGISTRY }}/blip:${{ inputs.image-tag }}

    - name: Creating new github tag
      uses: rickstaa/action-create-tag@v1
      with:
        tag: v${{ inputs.image-tag }}
        commit_sha: ${{ inputs.commit-sha }}
        force_push_tag: true
