import './unit/utils/utils.test.js'
import './unit/utils/personutils.test.js'
import './unit/components/chart/stats.test.js'
import './unit/components/chart/footer.test.js'
import './unit/components/messages/messages.test.js'
import './unit/components/messages/message.test.js'
import './unit/components/messages/messageform.test.js'
import './unit/lib/partial-data-load.test'
