language: node_js

os: linux
dist: bionic

node_js:
  - 10.15.3
  - lts/*

cache: npm
addons:
  chrome: stable
  firefox: latest-esr

before_install:
  - npm install -g npm@latest

install:
  - npm install

script:
  - npm run lint
  - npm run test
  - npm run security-checks
  - bash ./build.sh
