name: Publish on request

on:
  issue_comment:
    types: [created, edited]

env:
  GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
  PR_NUMBER: ${{ github.event.issue.number }}

jobs:
  get-current-branch:
    name: Get current branch
    runs-on: ubuntu-latest
    outputs:
      head-ref: ${{ steps.comment-branch.outputs.head_ref }}
      head-sha: ${{ steps.comment-branch.outputs.head_sha }}
    steps:
      - uses: xt0rted/pull-request-comment-branch@v1
        id: comment-branch

  build:
    name: Build
    if: ${{ github.event.issue.pull_request && github.event.comment.body == '/publish' }}
    needs: get-current-branch
    runs-on: ubuntu-latest
    steps:
      - name: Check for command
        id: command
        uses: xt0rted/slash-command-action@v1
        with:
          repo-token: ${{ secrets.GIT_TOKEN }}
          command: publish
          reaction: "true"
          reaction-type: "eyes"
          allow-edits: "false"
          permission-level: write

      - uses: actions/checkout@v3
        if: success()
        with:
          ref: ${{ needs.get-current-branch.outputs.head-ref }}

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
          cache-dependency-path: package-lock.json
          node-version: 16

      - name: Install npm dependencies
        run: npm ci

      - name: Build
        run: nice bash build.sh

      - name: Upload yourloops build
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/

  publish:
    name: Publish
    if: ${{ github.event.issue.pull_request && github.event.comment.body == '/publish' }}
    needs: [ get-current-branch, build ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v3
        if: success()
        with:
          ref: ${{ needs.get-current-branch.outputs.head-ref }}

      - name: Get YourLoops version from changelog
        uses: addnab/docker-run-action@v3
        with:
          username: ${{ secrets.NEXUS_USERNAME }}
          password: ${{ secrets.NEXUS_PASSWORD }}
          registry: ${{ secrets.REGISTRY }}
          options: -v ${{ github.workspace }}:/dblprm/blip:rw --user 0:0
          image: docker.ci.diabeloop.eu/ci-toolbox:latest
          run: |
            cd blip
            echo "semver=$(release-helper get-version)" > version.env

      - name: Read env file
        id: changelog-version
        uses: cardinalby/export-env-action@v1
        with:
          envFile: 'version.env'
          expand: 'false'
          export: 'false'

      - name: Publish
        uses: ./.github/workflows/publish.yml
        with:
          head-ref: ${{ needs.get-current-branch.outputs.head-ref }}
          image-tag: ${{ steps.changelog-version.outputs.semver }}-${{ env.PR_NUMBER }}
          commit-sha: ${{ needs.get-current-branch.outputs.head-sha }}
          registry: ${{ secrets.REGISTRY }}
          nexus-username: ${{ secrets.NEXUS_USERNAME }}
          nexus-password: ${{ secrets.NEXUS_PASSWORD }}
